### ISSUE TITLE
I am having an issue with build and running the apk

### ISSUE THREAD

**Issue by shreesha345** [CoolCoderSJ/HCGateway#5]
I tried many times and it gives the same error

```
> hcgateway@0.0.1 android
> react-native run-android

info Starting JS server...
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\HCGateway\app\android\settings.gradle' (C:\Users\shree\.gradle\caches\7.5.1\scripts\51n967gkkf0rk9vrfb37h9dep).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\HCGateway\app\android\settings.gradle' (C:\Users\shree\.gradle\caches\7.5.1\scripts\51n967gkkf0rk9vrfb37h9dep).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (D:\HCGateway\app\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\HCGateway\app\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\HCGateway\app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\HCGateway\app\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
```

**Comment by CoolCoderSJ** [comment]
what version android SDK/build tools and JDK do you have installed?

**Comment by shreesha345** [comment]
Which version download I need to install because currently I just installed react-native and it got the latest Java and installed it.

**Comment by CoolCoderSJ** [comment]
I just installed Android SDK 34 (but you should adjust this to your phone's needs), build tools 30.0.3, and JDK 17
If you have Java already it should be fine. 
To get android SDK and the build tools you can install the latest version of android studio and go through the setup

**Comment by CoolCoderSJ** [comment]
It is now also possible to use cloud build with github-actions and eas. The exact script I've been using can be found here- https://github.com/CoolCoderSJ/hc-app/blob/main/.github/workflows/build.yml

You will need to clone the app locally first, link it to an expo project, and add an EXPO_TOKEN to the secrets section of the build environment (on github).
